### ISSUE TITLE
[Bug] Compatibility with Sodium

### ISSUE THREAD

**Issue by seriousfreezing** [StartsMercury/visual-snowy-leaves#1]
First of all, I must thank you very much for developing this mod. It's been a huge contribution both to the community and to my Bedrock modpack. ✨❤️

Secondly, I tested your mod and had a hard time seeing the leaves turn white even when entering and exiting the game. Pressing F3+A, I had to re-enter the same world a few times for it to work. [Perhaps this problem is involved with Sodium support, as this is fixed when using Sodium]

Thirdly, the grass takes on a very strange color. [This doesn't happen if you don't use Sodium]

Fourthly, the particles stay white even when you break the leaf without it being white. [Also does not occur without Sodium]

![2024-11-11_02 03 24](https://github.com/user-attachments/assets/32953f19-ae79-4a0a-ad3d-ebab09827c46)
![2024-11-11_02 10 29](https://github.com/user-attachments/assets/93954dfb-c285-4fc4-8257-27f5cef3956d)

**Comment by StartsMercury** [comment]
1. Thanks! I had tried a mod, a while ago now, there's more than one I believe, like this and realized wont work when joining servers without it. Now I just got the motivation to try at it, though I had the concept in my mind, troubling me to "just do it" X).

2. I'm not sure how bad this is, but hopefully a new release on the way, adding a transition, hopefully helps. No longer needing F3 + A. Configuration may happen at a later release.

3. That is strange. The mod does modify specific textures so that it can be white, and it internally adjusts color application to account for. It should only be affecting the vanilla leaves the same to MCBE. I'll look into that next after the transition update.

4. I think the particle is fine, I'm thinking it's the actual blocks that's the problem. Those leaves should be white. Unless those are "roofed" leaves, which, I actually haven't tested, but it should probably work, also, since it uses the same check that now thinking, might also fail to account for that anyway.

**Comment by StartsMercury** [comment]
I've checked (2), I can't observe the issue with just Sodium and this mod (on 0.3.0, *new*). Perhaps you have a mod that changes grass?

**Comment by StartsMercury** [comment]
For (4), leaves turn white indoors, and so would the breaking particles. I may look into it at some point.

**Comment by seriousfreezing** [comment]
> I've checked (2), I can't observe the issue with just Sodium and this mod (on 0.3.0, _new_). Perhaps you have a mod that changes grass? Though already observable that it is happening, but this shouldn't happen ;-;, I had hardcoded which blocks to edit, something must be going horribly wrong.

In my tests I didn't use any other mods apart from: Fabric Api, Visual Snowy Leaves and Sodium

**Comment by seriousfreezing** [comment]
1. It's very difficult to find good ways that don't really affect the server side. I was thinking that you could use some kind of shaders.
2. I have to imagine that this bug is pretty bad because you need Sodium to be able to see the mod's effect.

**Comment by StartsMercury** [comment]
No... I couldn't get it to break. I'm trying random other mods now and I can't get the weird grass colours.

**Comment by seriousfreezing** [comment]
My test was only with Fabric API + Sodium + Visual Snowy Leaves. I create a new world, try to find a snowy biome via /locate and then press F3 + A and these bugs occur.

Maybe there's a software problem with this?

**Comment by Arrocha08** [comment]
I had the same grass color problem as @seriousfreezing on 0.2.2, but now on 0.3.0 is fixed and pretty.

**Comment by StartsMercury** [comment]
> I had the same grass color problem as @seriousfreezing on 0.2.2, but now on 0.3.0 is fixed and pretty.

Oh! I wasn't testing on 0.2.2, my bad! Well, good to know that's fixed now. Thank you @seriousfreezing and @Arrocha08 .

**Comment by seriousfreezing** [comment]
I've tested it again in this new version and all the bugs have been fixed, but when re-entering the world it will redo the entire leaf transition. If the transition has already been made, you shouldn't need to do it again.

**Comment by seriousfreezing** [comment]
![2024-11-13_21 34 03](https://github.com/user-attachments/assets/d9bbb1ac-07d1-45bd-900f-65269aa2d3c4)
Apparently detection is based on biome. I found a tree that is half and half, I think it would be difficult to detect the whole tree as well (maybe?)

**Comment by seriousfreezing** [comment]
> I've tested it again in this new version and all the bugs have been fixed, but when re-entering the world it will redo the entire leaf transition. If the transition has already been made, you shouldn't need to do it again.

Forget it, I compared it to the Bedrock edition and it's the same. Bedrock doesn't do it for the whole tree either, and the transition of the leaves always starts again.

**Comment by StartsMercury** [comment]
> I've tested it again in this new version and all the bugs have been fixed, but when re-entering the world it will redo the entire leaf transition. If the transition has already been made, you shouldn't need to do it again.

I had specific code for thay, but it wasn't working, I had revisit that. Though the simplest implementation would be, if it is raining/snowing, jump to the end of the transition, since the transition is not stored (reset everytime a world/level is created).

**Comment by StartsMercury** [comment]
> ![2024-11-13_21 34 03](https://github.com/user-attachments/assets/d9bbb1ac-07d1-45bd-900f-65269aa2d3c4)
> Apparently detection is based on biome. I found a tree that is half and half, I think it would be difficult to detect the whole tree as well (maybe?)

It's already weirder than what you think, it's per block! 3d biomes already supported (insert funny emoji). It's just using an already existing function thay checks if a specific block can experience snowfall.

**Comment by StartsMercury** [comment]
> Forget it, I compared it to the Bedrock edition and it's the same. Bedrock doesn't do it for the whole tree either, and the transition of the leaves always starts again.

Oh! I'll still consider adding a feature for the transition reset. QoL ig.

**Comment by seriousfreezing** [comment]
> I had specific code for that, but it wasn't working, I had revisit that. Though the simplest implementation would be, if it is raining/snowing, jump to the end of the transition, since the transition is not stored (reset everytime a world/level is created).

This transition would also be just a QOL, but I think someone might like that. I have to imagine that maybe this mod could have a QOL for flowers and snowy grasses, idk?

But I think if it's 3 values, yes it's 3D, since 2 would just be X and Y

**Comment by StartsMercury** [comment]
> This transition would also be just a QOL, but I think someone might like that. I have to imagine that maybe this mod could have a QOL for flowers and snowy grasses, idk?

Specifying additional blocks would be possible when the config is added. But thinking again, flowers can have multiple colours and that might not work well with the current system. For blocks like short grass or vines that have a single color, not much workaround is needed. I may look into using existing functionality in resource packs in dealing with multicoloured blocks.

**Comment by seriousfreezing** [comment]
No no, in the case of the flowers and grasses they wouldn't be turned gray but would be combined with a layer of snow. (Although the idea of the gray tone could be QOL)

**Comment by StartsMercury** [comment]
> No no, in the case of the flowers and grasses they wouldn't be turned gray but would be combined with a layer of snow. (Although the idea of the gray tone could be QOL)

Surely, there is a mod does this already, at least visually? I think connected grass mod, such as LambdaBetterGrass, already has it?

**Comment by seriousfreezing** [comment]
Yes, there is, but unfortunately because the mod developer no longer wants to work with this mod, it seems that there will be no more updates or porting to 1.21

There was a fork made by the community that does this, but it seems to be impossible to download.

**Comment by StartsMercury** [comment]
> Yes, there is, but unfortunately because the mod developer no longer wants to work with this mod, it seems that there will be no more updates or porting to 1.21

What about [BetterGrassify](https://modrinth.com/mod/bettergrassify), a fork of [ArdaGrass](https://modrinth.com/mod/ardagrass).

**Comment by seriousfreezing** [comment]
I've just tested this mod and it seems to be very close to what Bedrock is, so it's well worth it
