### ISSUE TITLE
[Suggestion] Mod name

### ISSUE THREAD

**Issue by Arrocha08** [StartsMercury/visual-snowy-leaves#2]
After the mod name you should write [Bedrock Parity] to catch people interest, and update to the newer versions as well.

**Comment by StartsMercury** [comment]
The name part, sure! Newer versions are planned, I think I only need to implement  the config and it's good for version porting.

**Comment by Arrocha08** [comment]
I know this might be too much but I got you a new icon as a little gift. If you like consider using.

![Untitled-2](https://github.com/user-attachments/assets/e89de02b-4735-4f85-962d-f4815588ed98)

**Comment by StartsMercury** [comment]
I may consider using this, thanks! I like the current one right now though, but we'll see if I change my mind!
